### PR TITLE
Correct fix for https://github.com/ClxS/SMAPI/issues/74

### PR DESCRIPTION
**Pull request by speeder**
The previous fix attempt DOES stop with the exceptions.

But legacy mods still doesn't work (they don't render anything at all).

This should fix it.

Also, on my test I had to uncomment "base.Draw()", when it was commented the screen rendered black on the mines, so it was impossible to test with the healthbar mods.

### CODE REVIEW

**Comment by ClxS** [comment]
I'll give it a try later on :) I'll leave this pull request open until I get chance to have a look!

**Comment by speeder** [comment]
Zoryn already did this on her own commits, making this one unecessary.

I am closing it.

I don't understand why it wasn't merged in first place though, it was a EXTREMELY simple change (I moved 2 lines from before a block, to after).

**Comment by speeder** [comment]
I will fix conflicts...

So, when Zoryn updated lots of stuff, I thought it made this commit necessary, because broken 0.39.2 mods started working again... except they ONLY work with zoom disabled, when zoomed stuff breaks anyway.

This code actually fixes it (makes 0.39.2 mods work correctly in 0.39.5+)

**Comment by speeder** [comment]
Done, can be merged now :)

**Comment by ClxS** [comment]
Mmm having a look, wouldn't it be best to put GraphicsEvents.InvokeDrawInRenderTargetTick(); before the screen is drawn to the backbuffer. (back where it was before 'fixed conflict')
I agree with putting Draw where it now is though. That'll fix compatibility issues with pre-0.39.2!

**Comment by speeder** [comment]
I never used InvokeDrawInRenderTargetTick before, so I dunno how it would behave, but you are correct!

**Pull request merged**
